name: deluxe_gc_admin
description: "Admin app for Deluxe GC"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  appwrite: ^12.0.4
  cached_network_image: 3.4.0
  community_material_icon: ^5.9.55
  cupertino_icons: ^1.0.8
  easy_image_viewer: ^1.5.1
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  focused_menu: ^1.0.5
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon.png

  android_12:
    image: assets/android12.png
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
